services:
  bancasempione.presentation.divise.webapi:
    image: ${DOCKER_REGISTRY-}bancasempionepresentationdivisewebapi
    build:
      context: .
      dockerfile: BancaSempione.Presentation.Divise.WebApi/Dockerfile
    ports:
        - "5000:5000"
        - "8080:8080"
    networks:
        - webnet
  bancasempione.infrastructure.divise.database:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=DemoRegistration12!"
    ports:
      - "1433:1433" #Per agevolare il debug
networks:
  webnet:
    driver: bridge
