services:
  bancasempione.presentation.divise.webapi:
    image: ${DOCKER_REGISTRY-}bancasempionepresentationdivisewebapi
    build:
      context: .
      dockerfile: BancaSempione.Presentation.Divise.WebApi/Dockerfile
    ports:
        - "8080:80"
        - "8081:8081"
#     networks:
#         - webnet

# networks:
#   webnet:
#     driver: bridge
